apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xenvironments.xbiglylabs.co.za
spec:
  group: xbiglylabs.co.za
  names:
    kind: XEnvironment
    plural: xenvironments
    shortNames:
      - "xenv"
      - "xenvs"
  claimNames:
    kind: Environment
    plural: environments
    shortNames:
      - "env"
      - "envs"
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.resourceRef.name
      name: CONNECT-TO
      type: string
    - jsonPath: .spec.compositionSelector.matchLabels.type
      name: TYPE
      type: string

    name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              test:
                type: boolean
